---
title: "analysis"
author: "Zhongxu"
date: 
output: html_document
---

# Figure 1 Consensus analysis

```{r}
library(foreach)
library(dplyr)

library(doParallel)
registerDoParallel(40)

library(utils)
pb <- utils::txtProgressBar(style = 3)

########################################## a) --> b) --> c)
outter.each.res <- foreach::foreach(i = 1:replicate, .combine = rbind) %dopar% {
  set.seed(seed + i)
  new_df <- df %>% sample_n(as.integer(nrow(df) * 0.85))
  new_df_analysis <- loonR::subtypeAssociationAnalysis(new_df, adjusted.hypergeometrix.p = adjusted.hypergeometrix.p, print.message = F)
  t <- new_df_analysis$cut.adjacencyMatrix
  mcl.res <- MCL::mcl(t, addLoops = T, inflation = 2.5)
  subtype.names <- colnames(t)

  inner.each.res <- foreach::foreach(cluster = unique(mcl.res$Cluster[mcl.res$Cluster != 0]), .combine = rbind) %do% {
    cluster.subtypes <- subtype.names[mcl.res$Cluster == cluster]
    if (length(cluster.subtypes) == 1) {
      c(cluster.subtypes, cluster.subtypes, 1)
    } else {
      comb <- loonR::generateCombinations(cluster.subtypes, size = 2, repeats = T)
      comb$Connected <- 1
      comb
    }
  }
  colnames(inner.each.res) <- c("Subtype1", "Subtype2", "Connected")
  inner.each.res$Boot <- i
  setTxtProgressBar(pb, i / replicate)
  data.frame(inner.each.res)
}
close(pb)


raw <- outter.each.res
group.df <- outter.each.res %>%
  dplyr::group_by(Subtype1, Subtype2) %>%
  dplyr::summarise(Freq = (n() / replicate))
rm(outter.each.res)

############################### construct consensus matrix from grouped dataframe
consensusMatrix <- reshape2::dcast(group.df, Subtype1 ~ Subtype2, value.var = c("Freq"))
rownames(consensusMatrix) <- consensusMatrix$Subtype1
consensusMatrix <- consensusMatrix[, -c(1)]

consensusMatrix <- loonR::fillSymmetricNATable(consensusMatrix)
consensusMatrix[is.na(consensusMatrix)] <- 0

consensusMatrix <- data.frame(consensusMatrix, check.names = F)


############################## adjacenty matrix
adjacencyMatrix <- consensusMatrix

# Identify consensus subtype
subtyping.res <- loonR::identifySubtypeFromMatrix(consensusMatrix, usingRawDf = T, adjacency.cutoff = adjacencyMatrixCutoff, clusterPrefix = subtype.prefix, inflation = 1.7)
adjacencyMatrix.proceed <- consensusMatrix

ConsensusSubtype.clean <- subtyping.res$cluster.df

# include study information
t.df <- t(df)
t.df.melt <- loonR::meltDataFrameByGroup(t.df, row.names(t.df))[, c(1, 3)] %>% unique()
colnames(t.df.melt) <- c("Study", "Subtype")

ConsensusSubtype.clean <- dplyr::full_join(ConsensusSubtype.clean, t.df.melt, by = c("Sample" = "Subtype"))
rm(t.df, t.df.melt)

subtype.count <- loonR::countClassByColumn(df)
ConsensusSubtype.clean <- dplyr::full_join(ConsensusSubtype.clean, subtype.count, by = c("Sample" = "Class", "Study" = "Column"))
rm(subtype.count)


if (sum(is.na(ConsensusSubtype.clean$Cluster)) != 0) {
  warning("Not found CMS subtype for the following type: ", ConsensusSubtype.clean$Sample[is.na(ConsensusSubtype.clean$Cluster)])
  stop("Please check the study and stype")
}

CMSCount <- ConsensusSubtype.clean %>%
  dplyr::group_by(Cluster) %>%
  dplyr::summarise(SubtypeCount = n())
CMSCount <- data.frame(CMSCount, row.names = CMSCount$Cluster) %>% dplyr::rename(Subtype = Cluster)

############################################## robustness of each subtype with a stability score
group.df$ConsensusSubtype1 <- subtyping.res$cluster.df$Cluster[match(group.df$Subtype1, subtyping.res$cluster.df$Sample)]
group.df$ConsensusSubtype2 <- subtyping.res$cluster.df$Cluster[match(group.df$Subtype2, subtyping.res$cluster.df$Sample)]

group.df$SameGroup <- group.df$ConsensusSubtype1 == group.df$ConsensusSubtype2

stability <- group.df %>%
  filter(SameGroup) %>%
  dplyr::rename(Subtype = ConsensusSubtype1) %>%
  dplyr::group_by(Subtype) %>%
  dplyr::summarise(Stability = mean(Freq))


############################################# Identify core samples
newlabels <- foreach(sample = rownames(df), .combine = rbind) %do% {
  sample.raw.subtype <- unlist(df[sample, ])
  sample.new.subtype <- ConsensusSubtype.clean$Cluster[match(sample.raw.subtype, ConsensusSubtype.clean$Sample)]
  sample.new.subtype <- as.character(sample.new.subtype)

  sig.count <- 0
  core.sample <- FALSE
  cms.type <- NA

  uniq.cms <- as.character(row.names(CMSCount))
  p.cms <- c()

  for (t.cms in uniq.cms) {
    t.pval <- phyper(sum(sample.new.subtype == t.cms) - 1,
      as.numeric(unclass(CMSCount[t.cms, c("SubtypeCount")])),
      as.numeric(unclass(sum(CMSCount$SubtypeCount) - CMSCount[t.cms, c("SubtypeCount")])),
      length(sample.new.subtype),
      lower.tail = F
    )

    if (t.pval <= 0.1) {
      sig.count <- sig.count + 1
      core.sample <- TRUE
      cms.type <- t.cms
    }
    # 20230321 add p value for each CMS
    p.cms <- c(p.cms, t.pval)
  }
  if (sig.count > 1) {
    cms.type <- "Confusing"
    core.sample <- FALSE
  }

  # Count appreance frequency
  subtype.count <- unlist(table(sample.new.subtype))
  if (sum(subtype.count == subtype.count[which.max(subtype.count)]) != 1) {
    HighFrequencySubtype <- "Confusing"
  } else {
    HighFrequencySubtype <- names(subtype.count)[which.max(subtype.count)]
  }
  p.cms <- as.numeric(format(p.cms, digits = 3))
  c(sample.new.subtype, core.sample, cms.type, HighFrequencySubtype, p.cms)
}


newlabels <- data.frame(newlabels, row.names = rownames(df))
colnames(newlabels) <- c(
  paste0("New", colnames(df)),
  "CoreSample", "CMSSubtype", "HighFrequencySubtype",
  paste0("P.", uniq.cms)
)

# Select CMS subtype based on p value 20230321
ttt <- loonR::findMaxMinColumnNamesForEachRow(newlabels,
  ties.method = "first",
  min = T, specified.column = seq(ncol(newlabels) - 3, ncol(newlabels))
)
newlabels$CMS.minP <- stringr::str_remove_all(ttt$Min.ColName, "P.")
newlabels$CMS.minP.value <- ttt$Min.Value
rm(ttt)

Samples <- cbind(df, newlabels)
rm(newlabels)

colnames(ConsensusSubtype.clean)[1] <- c("Subtype")
diag(consensusMatrix) <- 1
consensusMatrix <- data.frame(consensusMatrix, check.names = F)

############################################## 20211018 add plot
core.annotation.df <- res$Samples %>% filter(HighFrequencySubtype != "Confusing")
core.annotation.df <- core.annotation.df[, c(colnames(df), "HighFrequencySubtype")] # select by HighFrequencySubtype
colnames(core.annotation.df) <- c(colnames(df), "CMS")

cluster.info <- ConsensusSubtype.clean
```

# Figure 2
## Figure 2a

```{r}
library(maftools)

gistic.maf <- readGistic(
  gisticAllLesionsFile = "GISTIC/all_lesions.conf_95.txt",
  gisticAmpGenesFile = "GISTIC/amp_genes.conf_95.txt",
  gisticDelGenesFile = "GISTIC/del_genes.conf_95.txt",
  gisticScoresFile = "GISTIC//scores.gistic",
  isTCGA = FALSE
)

library(tidyr)
var.annovar <- var.annovar %>% separate(V76, c("GT", "AD", "AF", "DP"), ":")
var.annovar <- var.annovar %>% separate(AD, c("REF.DP", "ALT.DP"), ",")

var.annovar$DP <- as.numeric(var.annovar$DP)
var.annovar$AF <- as.numeric(var.annovar$AF)
var.annovar$ALT.DP <- as.numeric(var.annovar$ALT.DP)

# filter by DP and AF
var.annovar %<>% filter(ALT.DP >= 5 & AF >= 0.05) %>% filter(!ExAC_EAS > 0.05)


var.annovar.read <- read.maf(
  maf = var.annovar,
  clinicalData = tmp.clin.info,
  cnTable = gistic.maf@data[, 1:3] %>% filter(Hugo_Symbol %in% c(var.annovar$Gene.refGene)) %>% filter(as.character(Tumor_Sample_Barcode) %in% tmp.clin.info$Tumor_Sample_Barcode),
  vc_nonSyn = mutation.interesting
)

oncoplot(
  maf = var.annovar.read,
  draw_titv = FALSE,
  removeNonMutated = FALSE,
  clinicalFeatures = c("ECMS"),
  sortByAnnotation = T,
  annotationOrder = sort(unique(cms.group)),
  showTumorSampleBarcodes = F,
  annotationColor = col.list
)
```

## Figure 2b
```{r}
gene <- AnnotationDbi::mapIds(org.Hs.eg.db, keys = gene.name, keytype = "SYMBOL", column = "ENSEMBL")

rm(tmp.df)
tmp.df <- all.rna.rsem.log[gene, names(cms.group)]
tmp.df <- data.frame(
  MESCC = as.factor(as.character(cms.group)),
  Expression = tmp.df,
  stringsAsFactors = F
)

my_comparisons <- list(c("ECMS1", "ECMS2"), c("ECMS1", "ECMS3"), c("ECMS1", "ECMS4"), c("ECMS2", "ECMS3"), c("ECMS2", "ECMS4"), c("ECMS3", "ECMS4"))

p <- ggplot(tmp.df, aes(y = Expression, x = MESCC, group = MESCC, fill = MESCC)) +
  geom_boxplot() +
  ggtitle(paste("Expression", gene, gene.name, sep = "\t")) +
  scale_fill_manual(values = pal_lancet("lanonc")(5)) +
  theme_bw() +
  xlab("") +
  ylab("") +
  scale_alpha_manual(values = c(1, 0.1)) +
  theme(axis.text.x = element_blank()) +
  stat_compare_means(method = "wilcox.test", comparisons = my_comparisons, label.y = c(13, 14, 15, 16, 17, 18)) +
  stat_compare_means()
```

## Figure 2c

```{r}
color.p <- c("#4074A8", "#F24040", "#71C870", "#40B3C7") # alpha = 0.75

seg.raw <- read.table("FACETS.logratio.tsv", header = F, stringsAsFactors = FALSE)

library(magrittr)
seg.raw %<>% filter(V7 != "NEUTR") %>% filter(V1 %in% names(cms.group))

seg.raw <- unclass(table(seg.raw$V7, seg.raw$V1))

match(colnames(seg.raw), names(cms.group))

tmp.df <- data.frame(
  Count = apply(seg.raw, 2, sum),
  ECMS = factor(paste0("", cms.group)),
  stringsAsFactors = FALSE
)

my_comparisons <- list(
  c("ECMS1", "ECMS2"), c("ECMS1", "ECMS3"), c("ECMS1", "ECMS4"),
  c("ECMS2", "ECMS3"), c("ECMS2", "ECMS4"), c("ECMS3", "ECMS4")
)

p.cnv <- ggpubr::ggboxplot(
  tmp.df,
  y = "Count", x = "ECMS", fill = "ECMS",
  palette = color.p, legend = "none",
  ylab = "Count", xlab = ""
) + ggtitle("SCNA segment count (gain and loss)") + rotate_x_text(angle = 0) +
  stat_compare_means(
    method = "wilcox",
    comparisons = my_comparisons
  )

p.cnv
```

## Figure 2d

```{r}
var.annovar %<>% filter(Func.refGene == "exonic")

tmb.df <- maftools::tmb(
  maftools::read.maf(maf = var.annovar),
  captureSize = 100, logScale = TRUE
)

tmb.df <- tmb.df[match(names(cms.group), tmb.df$Tumor_Sample_Barcode), ]
tmb.df$Samples <- names(cms.group)
tmb.df$MESCC <- factor(paste0("", cms.group))

tmb.df$total_perMB <- as.numeric(tmb.df$total_perMB)

p.tmb <- ggpubr::ggboxplot(
  tmb.df,
  y = "total_perMB", x = "MESCC", fill = "MESCC",
  palette = color.p, legend = "none",
  ylab = "TMB", xlab = ""
) + ggtitle("Tumor mutation burden") + rotate_x_text(angle = 0) +
  stat_compare_means(
    method = "wilcox", method.args = list(alternative = "great"),
    comparisons = list(
      c("ECMS1", "ECMS3"),
      c("ECMS2", "ECMS3"),
      c("ECMS4", "ECMS3")
    )
  )
p.tmb
```

## Figure 2e
```{r}
kmt2d.df <- data.frame(
  SNF = c("ECMS1", "ECMS2", "ECMS3", "ECMS4"),
  Mutation = c(4, 12, 1, 6),
  Total = c(32, 69, 27, 24)
)

df <- kmt2d.df
df$Ratio <- df$Mutation / df$Total

library(ggpubr)
p.mutation <- ggbarplot(df,
  x = "SNF", y = "Ratio", fill = "SNF",
  palette = color.p, ylim = c(0, 0.3),
  ylab = "Mutated gene ratio", xlab = "", legend = "none"
)
p.mutation
```

## Figure 2f

```{r}
gene <- "ENSG00000130303" # BST2

df <- data.frame(x = data.list$Methylation.Ensembl.Promoter[gene, ], y = log2(data.list$RNA.tpm[gene, all.cms.samples] + 1), SNF = as.factor(all.cms.group))

ggscatter(df, "x", "y",
  cor.coef = T,
  cor.method = "spearman",
  xlab = "β value", ylab = "log2(TPM+1)",
  add = "reg.line", facet.by = "SNF"
)

p.methylation <- ggboxplot(df,
  x = "SNF", y = "x", fill = "SNF",
  palette = color.p, legend = "none",
  ylab = "β value", xlab = ""
) + rotate_x_text(90) +
  stat_compare_means(
    method = "wilcox",
    comparisons = list(
      c("ECMS2", "ECMS1"),
      c("ECMS2", "ECMS4"),
      c("ECMS3", "ECMS4"),
      c("ECMS3", "ECMS1"),
      c("ECMS2", "ECMS3")
    )
  )
p.methylation
```

## Figure 2g
```{r}
library(reshape)
library(HTSanalyzeR2)
library(limma)

rna.rsem.log <- log2(data.list$RNA.tpm[rowMeans(data.list$RNA.tpm)>0.5, ]+1)

load("geneset.gmt.rdata")
cat("unMatched samples: ", sum( names(cms.group)!=colnames(rna.rsem.log))  )

############################################################################# Function
function.analysis.clean.res <- loonR::compare_GSE.HTSAnalyzer(rna.rsem.log, cms.group, prefix = "", customGS = CustomGS)
function.analysis.clean.res <- function.analysis.clean.res$heatmap.df


######################################for custom gene set
term.signature <- c("EPITH_LOBODA", "WNT_FLIER", "MYC_TARGETS_CP", "MESENCH_LOBODA", "EMT_CORE_GENES", "TGFB_KEGG", "MATRIX_REMODEL_REACTOME", "WOUND_RESPONSE_GO_BP","CSC_BATLLE","HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION","dbEMT")

term.pathway <- c("MAPK_KEGG","PI3K_ACT_REACTOME","SRC_ACT_BIOCARTA","JAK_STAT_KEGG","CASPASE_BIOCARTA","PROTEASOME_KEGG","KEGG_CELL_CYCLE","TRANSLATION_RIBOS_REACTOME","INTEGRIN_BIOCARTA","VEGF_VEGFR_REACTOME", "HALLMARK_NOTCH_SIGNALING")

term.estimate <- c("IMMUNE_ESTIMATE", "STROMAL_ESTIMATE")

term.immune <- c( "PD1_REACTOME",row.names(function.analysis.clean.res)[grep("IMMUNE",row.names(function.analysis.clean.res))],  "COMPLEMENT_BIOCARTA")

term.metabolism <- c("AMINO_SUGAR_NUCLEO_METAB_KEGG","PENTOSE_GLUC_METAB_KEGG", "FRUTOSE_MANNOSE_METAB_KEGG", "GALACTOSE_METAB_KEGG","GLUTAMINE_GO_BP","GLUTATHIONE_KEGG","NITROGEN_METAB_KEGG","GLYCEROPHOSPHOLIPID_METAB_KEGG","LYSOPHOSPHOLIPID_PID","FATTY_ACID_METAB_KEGG")

term.emt <- c("REACTOME_TGF_BETA_RECEPTOR_SIGNALING_IN_EMT","HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION","dbEMT","ALONSO_METASTASIS_EMT_UP")
######################################for custom gene set

anncolors = ggsci::pal_lancet("lanonc")(length(unique(cms.group)))
anncolors = color.p

names(anncolors) =  colnames(function.analysis.clean.res) # 
breaks <- seq(-2, 2, length.out=51)

gaps_row = c(length(term.signature), length(term.pathway), length(term.estimate), length(term.immune), length(term.metabolism), length(term.emt))
gaps_row = cumsum(gaps_row)

pheatmap::pheatmap(
  function.analysis.clean.res[c(term.signature,
                                term.pathway,
                                term.estimate,
                                term.immune, 
                                term.metabolism,
                                term.emt
                                ), ], #
  scale = "none",
  gaps_row = gaps_row,
  cluster_rows = F, cluster_cols =F,
  #color = colorRampPalette(c("#6b943c", "white", "#b60505"))(50),
  color = colorRampPalette(c("#90AF6D", "white", "#C84444"))(50),
  breaks = breaks,
  cellwidth = 10, cellheight = 10,
  annotation_col = data.frame(row.names = colnames(function.analysis.clean.res),
    ECMS=as.factor(colnames(function.analysis.clean.res))
    ),
  show_colnames = FALSE, annotation_legend = F, legend = FALSE, 
  annotation_colors = list(ECMS=anncolors)
)

snf_anncolors = pal_lancet("lanonc")(4)
names(snf_anncolors) = paste("ECMS",sort(unique(cms.group)),sep="")

```

# Figure 3

```{r}
df <- data.frame(
  Gender = clin.info$Gender,
  Age = as.numeric(clin.info$Age),
  Recurrence = clin.info$Recurrence_or_metastasis == 1,
  Location = clin.info$Location,
  Personal.history = clin.info$personal.history == 1,
  Family.history = clin.info$Family.History.of.ESCC == 1,
  Smoking.history = clin.info$Smoking.history,
  Drinking.history = clin.info$Drinking.history,
  Perineural.invasion = clin.info$Perineural.Invasion.PNI. == 1,
  Intravascular.cancer.embolus = clin.info$Intravascular.cancer.embolus == 1,
  Grade = clin.info$Grade,
  T = clin.info$T,
  N = clin.info$N,
  row.names = names(cms.group)
)

age.fun <- circlize::colorRamp2(c(40, 60, 80), c("white", "gray", "black"))
Gender.col <- c("Female" = "gray", "Male" = "black")
recurrence.col <- c("TRUE" = "#ed90a3", "FALSE" = "#e7e7e7")

location.col <- loonR::get.palette.color("npg", 3, alpha = 0.8)
names(location.col) <- unique(df$Location)

smoke.drink.col <- c("never" = "#cee6d0", "light" = "#66de94", "moderate" = "#ff626d", "heavy" = "#da0037")

grade.col <- loonR::get.palette.color("Dark2", 3)
names(grade.col) <- unique(clin.info$Grade)

tnm.col <- loonR::get.palette.color("Set3", 4)
names(tnm.col) <- 0:3


col.list <- list(
  Age = age.fun, Gender = Gender.col,
  Recurrence = recurrence.col, Location = location.col,
  `Personal.history` = recurrence.col, `Family.history` = recurrence.col,
  Smoking.history = smoke.drink.col, Drinking.history = smoke.drink.col,
  Perineural.invasion = recurrence.col,
  Intravascular.cancer.embolus = recurrence.col,
  Grade = grade.col, T = tnm.col, N = tnm.col
)


loonR::heatmap.annotation(cms.group, annotation.df = df, col.list, group.color = "lancet")
```
