---
title: "image_analysis_for_imECMS_Fig4&5"
author: "Yinghan"
date: 
output: html_document
---

```{r}
#Prepare packages and functions
options(java.parameters = "-Xmx50g")
library(bartMachine)
library(doParallel)
library(stringr)
library(car)
library(stringr)
library(ggpubr)
library(ggplot2)
library(cowplot)
library(caret)
library(ggalluvial)
#Function to calculate p-value
P_cal <- function(clinical,labels){
            time <- clinical[, 1]
            event <- clinical[, 2] == 1
            df <- data.frame(futime = time, fustat = event, group = labels)
            surv <- survival::survfit(survival::Surv(futime, fustat) ~ 
                                        group, data = df)
            survstats <- survival::survdiff(survival::Surv(futime, fustat) ~ 
                                              group, data = df)
            survstats$p.value <- 1 - pchisq(survstats$chisq, length(survstats$n) - 
                                              1)
            return(survstats$p.value)
}
#OS_KM_Plot_function
myplot <- function (clinical, labels, limit = NULL, annot = NULL, color = NULL, 
  font = "Arial", xlab = "Follow up", ylab = "Survival Probability", 
  title = NULL, legend.pos = "top", palette = "jama_classic", 
  risk.table = T, risk.table.ratio = 0.4, anno.pos = "bottom", 
  anno.x.shift = 0.5) 
{
  time <- clinical[, 1]
  event <- clinical[, 2] == 1
  if (!is.null(limit)) {
    event[time > limit] <- F
    time[time > limit] <- limit
  }
  df <- data.frame(futime = time, fustat = event, group = labels)
  surv <- survival::survfit(survival::Surv(futime, fustat) ~ 
    group, data = df)
  survstats <- survival::survdiff(survival::Surv(futime, fustat) ~ 
    group, data = df)
  survstats$p.value <- 1 - pchisq(survstats$chisq, length(survstats$n) - 
    1)
  if (!is.null(color)) {
    if (!is.null(names(color))) {
      labels <- factor(labels, levels = names(color))
    }
  }
  else {
    color <- get_color(palette, n = length(unique(labels)))
  }
  if (class(labels) == "factor") {
    legend.labs <- na.omit(levels(droplevels(labels[!(is.na(time) | 
      is.na(event))])))
  }
  else if (class(labels) == "logical") {
    labels <- factor(labels, levels = c(F, T))
    legend.labs <- na.omit(levels(droplevels(labels)))
  }
  else {
    legend.labs <- na.omit(unique(labels))
    labels <- factor(labels, levels = legend.labs)
  }
  fancy_scientific <- function(l, dig = 3) {
    l <- format(l, digits = dig, scientific = TRUE)
    l <- gsub("^(.*)e", "'\\1'e", l)
    l <- gsub("e", "%*%10^", l)
    parse(text = l)
  }
  p <- survminer::ggsurvplot(surv, data = df, xlab = xlab, 
    ylab = ylab, palette = color, legend = legend.pos, legend.labs = legend.labs, 
    risk.table = risk.table, risk.table.title = element_blank(), 
    risk.table.y.text = FALSE, ggtheme = cowplot::theme_cowplot())
  p$plot <- p$plot + ggtitle(title) + theme(plot.title = element_text(hjust = 0.5), 
    text = element_text(family = font), title = element_text(family = font), 
    axis.text.x = element_text(family = font), legend.title = element_blank())
  anno.text <- ifelse(survstats$p.value == 0, "italic(P)<1%*%10^{-22}", 
    paste0("italic(P)==", fancy_scientific(survstats$p.value, 
      3)))
  anno.y.shift <- 0
  if (length(legend.labs) == 2) {
    hr <- survcomp::hazard.ratio(labels[!(is.na(time) | 
      is.na(event))], time[!(is.na(time) | is.na(event))], 
      event[!(is.na(time) | is.na(event))])
    anno.text <- c(anno.text, sprintf("HR == %3.2f~(%3.2f - %3.2f)", 
      hr$hazard.ratio, hr$lower, hr$upper))
    anno.y.shift <- c(anno.y.shift + 0.15, 0)
  }
  if (!is.null(annot)) {
    anno.text <- c(anno.text, annot)
    anno.y.shift <- c(anno.y.shift + 0.15, 0)
  }
  if (anno.pos == "bottom") {
    p$plot <- p$plot + annotate("text", family = font, x = 0, 
      y = anno.y.shift, label = anno.text, hjust = 0, 
      vjust = 0, parse = TRUE)
  }
  else {
    p$plot <- p$plot + annotate("text", family = font, x = anno.x.shift * 
      max(time, na.rm = T), y = 0.85 + anno.y.shift, label = anno.text, 
      hjust = 0, vjust = 2, parse = TRUE)
  }
  if (risk.table) {
    p$table <- p$table + theme(text = element_text(family = font), 
      title = element_text(family = font), axis.text = element_text(family = font), 
      axis.title.y = element_blank())
    pp <- plot_grid(plotlist = list(p$plot + theme(axis.title.x = element_blank()), 
      p$table + labs(x = xlab)), labels = "", ncol = 1, 
      align = "v", rel_heights = c(1, risk.table.ratio))
    return(pp)
  }
  else return(p$plot)
}

source("./distri_barplot.R")
```


```{r}
load("./core_sample.rdata")
load("./SXMI_Clinical.rdata")
load("./SXMI_SOFs.rdata")
load("./label4slide.rdata")
load("./roc_scores.rdata")
load("./label4slide_coresample.rdata")
```



```{r}
#install extraTrees and dummies if you don't have one
#install.packages("./extraTrees_1.0.5.tar.gz", repos = NULL, type = "source")
#install.packages("./dummies_1.5.6.tar.gz", repos = NULL, type = "source")
##Analysis of underrepresented subtypes && screening and new samples

ntree <- 100
mtry <- 2
numRandomCuts <- 2
nodesize <- 2

Counts <- lapply(1:100,function(Times){
  set.seed(Times)
  ind <- sample(1:nrow(SXM_I_coreSOFs),ceiling(0.9*nrow(SXM_I_coreSOFs)),replace = FALSE)
  trainD <- SXM_I_coreSOFs[ind,]
  trainL <- Label4slides_coresample[ind]
  testD <- SXM_I_coreSOFs[-ind,]
  testL <- Label4slides_coresample[-ind]
  rfout <- extraTrees::extraTrees(trainD, trainL, ntree=ntree,mtry = mtry, numRandomCuts = numRandomCuts,nodesize=nodesize,numThreads = 8)
  rfpred <- predict(rfout, testD) 
  tmp <- rfpred==testL
  names(tmp) <- rownames(testD)
  gc()
  return(tmp)
})

Counts <- do.call(c,Counts)

uniqueNames <- unique(names(Counts))

ratio <- sapply(uniqueNames, function(xxx){
  tmp <- which(names(Counts)==xxx)
  tmp_ratio <- mean(Counts[tmp])
  return(tmp_ratio)
})

ratio <- ratio[match(names(Label4slides_coresample),names(ratio))] # !!!!!!
ind_discard <- which(ratio<=0.1)

Label4slides_coresample_selected <- Label4slides_coresample[-ind_discard]
temp1=as.data.frame(Label4slides_coresample_selected)

Label4slides_coresample_freq <- table(Label4slides_coresample)
Label4slides_coresample_selected_freq <- table(Label4slides_coresample_selected)
represent_ratio <- Label4slides_coresample_selected_freq / Label4slides_coresample_freq

print(represent_ratio)

SXM_I_coreSOFs <- SXM_I_coreSOFs[-ind_discard,]

Names <- substr(rownames(SXM_I_coreSOFs),3,9)
uniqueName <- unique(Names)
```

```{r}
All_100 <- sapply(1:100, function(xxx){
  rfpredBB <- Label4slides_selected
  prob = matrix(nrow = length(Label4slides_selected), ncol = 4)
  index = rep(1:10, nrow(SXM_I_coreSOFs))
  ind = index[1:nrow(SXM_I_coreSOFs)]
  # seed <- sample(1:100000,1)
  # set.seed(seed)
  ind <- sample(ind) # suffle 
  
  for (k in 1:10) {
    xcal <- SXM_I_coreSOFs[ind != k, ] 
    ycal <- Label4slides_selected[ind != k]
    xtest <- SXM_I_coreSOFs[ind == k, ] 
    ytest <- Label4slides_selected[ind == k]   
    train_df <- cbind(xcal,ycal)
    rfout <- extraTrees::extraTrees(xcal, ycal, ntree=ntree,mtry = mtry, numRandomCuts = numRandomCuts,nodesize=nodesize) # 
   
    rfpredBB[ind == k] = predict(rfout, xtest) 
    prob[ind == k, ] = predict(rfout, xtest, probability = TRUE)
  }
  res <- table(rfpredBB,Label4slides_selected)
  ACC = sum(diag(res))/length(Label4slides_selected)
  true_label <- dummies::dummy(Label4slides_selected) # true label
  true_label <- data.frame(true_label)
  colnames(true_label) <- paste(colnames(true_label), "_true")
  pre <- prob
  colnames(pre) <- str_replace(colnames(true_label),"_true","_pred_RF")
  final_df <- cbind(true_label, pre)
  roc_res <- multiROC::multi_roc(final_df, force_diag=T)
  AUC_each <- as.numeric(unlist(roc_res$AUC))
  AUC_each <- round(AUC_each,digits = 3)
  return(c(ACC,AUC_each))
})
All_100 <- t(All_100)
colnames(All_100) <- c("ACC","Class1","Class2","Class3","Class4","macro","micro")

aa <- All_100[,-1]
aa <- reshape2::melt(aa)
colnames(aa) <- c("sample","group","AUC")
AA <- ggplot(aa, aes(x=group, y=AUC,color=group)) + 
  geom_boxplot()+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_manual(values=c("#00468BFF","#ED0000FF","#42B540FF","#0099B4FF","dimgray","gray"))+
  ylim(c(0.0,1))+
  geom_hline(yintercept = 0.8,color="red",linetype="dashed",size=1)
AA
```
```{r}
result_list <- list()

for (xxx in 1:100) {
  rfpredBB <- Label4slides_selected
  prob <- matrix(nrow = length(Label4slides_selected), ncol = 4)
  index <- rep(1:10, nrow(SXM_I_coreSOFs))
  ind <- index[1:nrow(SXM_I_coreSOFs)]
  ind <- sample(ind)  # suffle 
  
  for (k in 1:10) {
    xcal <- SXM_I_coreSOFs[ind != k, ] 
    ycal <- Label4slides_selected[ind != k]
    xtest <- SXM_I_coreSOFs[ind == k, ] 
    ytest <- Label4slides_selected[ind == k]   
    train_df <- cbind(xcal, ycal)
    rfout <- extraTrees::extraTrees(xcal, ycal, ntree = ntree, mtry = mtry, numRandomCuts = numRandomCuts, nodesize = nodesize)
   
    rfpredBB[ind == k] <- predict(rfout, xtest) 
    prob[ind == k, ] <- predict(rfout, xtest, probability = TRUE)
  }
  
  true_label <- dummies::dummy(Label4slides_selected)  # true label
  true_label <- data.frame(true_label)
  colnames(true_label) <- paste(colnames(true_label), "_true")
  pre <- prob
  colnames(pre) <- str_replace(colnames(true_label), "_true", "_pred_RF")
  final_df <- cbind(true_label, pre)
  
  # Store each column as a vector
  result_list[[xxx]] <- list(
    Class1_true = final_df$`Label4slides_selectedECMS1 _true`,
    Class2_true = final_df$`Label4slides_selectedECMS2 _true`,
    Class3_true = final_df$`Label4slides_selectedECMS3 _true`,
    Class4_true = final_df$`Label4slides_selectedECMS4 _true`,
    Class1_pred_RF = final_df$`Label4slides_selectedECMS1 _pred_RF`,
    Class2_pred_RF = final_df$`Label4slides_selectedECMS2 _pred_RF`,
    Class3_pred_RF = final_df$`Label4slides_selectedECMS3 _pred_RF`,
    Class4_pred_RF = final_df$`Label4slides_selectedECMS4 _pred_RF`
  )
}

# Extract each vector from the result list
ECMS1.labels <- sapply(result_list, function(x) x$Class1_true)
ECMS2.labels <- sapply(result_list, function(x) x$Class2_true)
ECMS3.labels <- sapply(result_list, function(x) x$Class3_true)
ECMS4.labels <- sapply(result_list, function(x) x$Class4_true)

ECMS1.scores <- sapply(result_list, function(x) x$Class1_pred_RF)
ECMS2.scores <- sapply(result_list, function(x) x$Class2_pred_RF)
ECMS3.scores <- sapply(result_list, function(x) x$Class3_pred_RF)
ECMS4.scores <- sapply(result_list, function(x) x$Class4_pred_RF)

ECMS1.labels <- c(ECMS1.labels)
ECMS2.labels <- c(ECMS2.labels)
ECMS3.labels <- c(ECMS3.labels)
ECMS4.labels <- c(ECMS4.labels)

ECMS1.scores <- c(ECMS1.scores)
ECMS2.scores <- c(ECMS2.scores)
ECMS3.scores <- c(ECMS3.scores)
ECMS4.scores <- c(ECMS4.scores)
```

```{r}
require(pROC)
require(ggplot2)
library(doParallel)
library(pROC)
scores = list(ECMS1 = ECMS1.scores, ECMS2 = ECMS2.scores,ECMS3 = ECMS3.scores, ECMS4 = ECMS4.scores)
labels = list(ECMS1 = ECMS1.labels, ECMS2 = ECMS2.labels,ECMS3 = ECMS3.labels, ECMS4 = ECMS4.labels)
# roc line colors. e.g. if two rocs. color = c("black","red")
color = c("#00468BFF","#ED0000FF","#42B540FF","#0099B4FF")
########################################

set.seed(100)
roclist <- lapply(1:length(scores), function(i){
      index <- !is.na(scores[[i]])
      pROC::roc(labels[[i]][index], scores[[i]][index])
 })
 names(roclist) <- names(scores)
 dat.ci <- data.frame( x=NA, se.lower=NA, se.upper=NA, group = NA, y =NA, sp.lower = NA, sp.upper = NA )
 for(group_name in names(roclist)){
        registerDoParallel(10)
        se.ciobj <- ci.se(roclist[[group_name]], specificities = seq(0, 1, l = 100), boot.n = 2000, parallel = TRUE)
        registerDoParallel(10)
        sp.ciobj <- ci.sp(roclist[[group_name]], sensitivities = seq(0, 1, l = 100), boot.n = 2000, parallel = TRUE)
        dat.ci.tmp <- data.frame(x = as.numeric(rownames(se.ciobj)), se.lower = se.ciobj[, 1], se.upper = se.ciobj[, 3],  group = group_name, y = as.numeric(rownames(sp.ciobj)), sp.lower = sp.ciobj[, 1], sp.upper = se.ciobj[, 3] )
        dat.ci <- rbind(dat.ci, dat.ci.tmp)
}
dat.ci <- dat.ci[-c(1),]
annot <- c()
aucs <- c()
for(group_name in names(roclist)){
    auc <- pROC::ci(roclist[[group_name]])[c(2, 1, 3)]
    others <- pROC::coords(roclist[[group_name]], "best", ret = c("sensitivity", "specificity"), best.policy = "omit")

    annot <- c(annot, sprintf("%.2f (%.2f-%.2f)", auc[1], auc[2], auc[3])  ) # 常用，AUC CI 
    aucs <- c(aucs, auc[1])
}
annot <- paste0(stringr::str_pad(names(roclist), max(sapply(names(roclist), nchar))+1, "right"), "\t", annot)
colors <- color
names(colors) <- names(roclist)

roc_curve=pROC::ggroc(roclist, legacy.axes = TRUE, size=0.93) +  labs(x = "1 - Specificity", y = "Sensitivity") + scale_color_manual(labels = annot, values = colors ) + theme_classic() +  geom_abline(linetype = "dashed", alpha = 0.3) + coord_equal() + geom_ribbon( data = dat.ci, inherit.aes = FALSE, show.legend = FALSE, aes(x = 1-x, xmin = 1-sp.upper, xmax = 1-sp.lower, y =y, ymin = se.lower, ymax = se.upper, group=group, fill=as.factor(group)), alpha = 0.1) + scale_fill_manual(values=colors) + theme(legend.title = element_blank()) 

roc_curve
```


```{r}
#Figure 4D

# barplot
Matrix <- SXMI_SOFs
Matrix$Subtype <- Label4slides
index1 <- which(Label4slides== "1")
index2 <- which(Label4slides== "2")
index3 <- which(Label4slides== "3")
index4 <- which(Label4slides== "4")

# all raw
con <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratiocon,title = "Connective")
epi <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratioepi,title = "Epithelium")
gla <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratiogla,title = "Glands")
lym <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratiolym,title = "Lymphocyte")
mus <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratiomus,title = "Muscle")
str <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratiostr,title = "Stroma")
tum <- distri_barplot(Matrix = (Matrix),index = Matrix$WS_infil_ratiotum,title = "Tumor")

aa <- plot_grid(con[[1]],epi[[1]],gla[[1]],lym[[1]],mus[[1]],str[[1]],tum[[1]],ncol = 3,align = "hv")

# + pvalues
a1 <- round(wilcox.test(Matrix$WS_infil_ratiocon[index2],Matrix$WS_infil_ratiocon[-index2])$p.value,3)
if(a1==0){a1 = "< 0.001"}
con2 <- con[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS2 vs. others: ",a1), vjust=1, hjust=0,size = 5)

a1 <- round(wilcox.test(Matrix$WS_infil_ratioepi[index3],Matrix$WS_infil_ratioepi[-index3])$p.value,3)
if(a1==0){a1 = "< 0.001"}
epi2 <- epi[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS3 vs. others: ",a1), vjust=1, hjust=0,size = 5)

a1 <- round(wilcox.test(Matrix$WS_infil_ratiogla[index3],Matrix$WS_infil_ratiogla[-index3])$p.value,3)
if(a1==0){a1 = "< 0.001"}
gla2 <- gla[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS3 vs. others: ",a1), vjust=1, hjust=0,size = 5)

a1 <- round(wilcox.test(Matrix$WS_infil_ratiolym[index3],Matrix$WS_infil_ratiolym[-index3])$p.value,3)
if(a1==0){a1 = "< 0.001"}
lym2 <- lym[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS3 vs. others: ",a1), vjust=1, hjust=0,size = 5)

a1 <- round(wilcox.test(Matrix$WS_infil_ratiomus[index3],Matrix$WS_infil_ratiomus[-index3])$p.value,3)
if(a1==0){a1 = "< 0.001"}
mus2 <- mus[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS3 vs. others: ",a1), vjust=1, hjust=0,size = 5)

a1 <- round(wilcox.test(Matrix$WS_infil_ratiostr[index4],Matrix$WS_infil_ratiostr[-index4])$p.value,3)
if(a1==0){a1 = "< 0.001"}
str2 <- str[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS4 vs. others: ",a1), vjust=1, hjust=0,size = 5)

a1 <- round(wilcox.test(Matrix$WS_infil_ratiotum[index2],Matrix$WS_infil_ratiotum[-index2])$p.value,3)
if(a1==0){a1 = "< 0.001"}
tum2 <- tum[[1]] + annotate("text",  x=0.5, y = Inf, label = paste0("ECMS2 vs. others: ",a1), vjust=1, hjust=0,size = 5)

aa2 <- plot_grid(con2,epi2,gla2,lym2,mus2,str2,tum2,ncol = 3,align = "hv")
aa3 <- plot_grid(con2,epi2,gla2,mus2,str2,ncol = 3,align = "hv")

```

```{r}
#Figure 4E

wilcox.test(as.numeric(EstimateScore$ImmuneScore[which(EstimateScore$Subtype=="ECMS1")]), 
            as.numeric(EstimateScore$ImmuneScore[which(EstimateScore$Subtype!="ECMS1")]))

wilcox.test(as.numeric(EstimateScore$TumorPurity[which(EstimateScore$Subtype=="ECMS2")]), 
            as.numeric(EstimateScore$TumorPurity[which(EstimateScore$Subtype!="ECMS2")]))
wilcox.test(as.numeric(EstimateScore$TumorPurity[which(EstimateScore$Subtype=="ECMS3")]), 
            as.numeric(EstimateScore$TumorPurity[which(EstimateScore$Subtype!="ECMS3")]))

# barplot
Matrix <- EstimateScore
Matrix$Subtype <- str_replace_all(EstimateScore$Subtype,"ECMS","")

lym_plot <- distri_barplot(Matrix = (Matrix),index = Matrix$ImmuneScore,title = "ImmuneScore")
tum_plot <- distri_barplot(Matrix = (Matrix),index = Matrix$TumorPurity,title = "TumorPurity")

plot_grid(lym_plot[[1]],tum_plot[[1]],ncol = 2,align = "hv")

```


```{r}
#Figure 5 C&D&G
load("./rst_final_model.rdata")
load("./SXMI_SOFs_310.rdata")
xtest <- SXMI_SOFs_310
Pred_SXMI <- predict(final_model,xtest)
pred_SXMI_prob <- predict(final_model,xtest, probability=TRUE)


Names <- substr(rownames(SXMI_SOFs_310),3,9)
uniqueName <- unique(Names)


Vote_max_slides_SXMI <- list()
frequency_table_list <- list()

for (xxx in uniqueName) {
  ind <- which(Names == xxx)  
  all_result <- Pred_SXMI[ind[1]:ind[length(ind)]]
  frequency_table <- table(all_result)
  frequency_table_list[[xxx]] <- frequency_table
  if (sum(frequency_table == max(frequency_table)) >= 2) {
    back <- NA
  }else {
    most_frequent_element <- names(frequency_table)[which.max(frequency_table)]
    back <- most_frequent_element
  }
  if (frequency_table[which.max(frequency_table)] != length(ind) && frequency_table[4] > 0) {
    back <- "ECMS4"
  }
  Vote_max_slides_SXMI[[xxx]] <- back  # 将结果存储在列表中
}

names(Vote_max_slides_SXMI) <- uniqueName
Vote_max_slides_SXMI <- do.call(c,Vote_max_slides_SXMI)

Vote_max_slides_SXMI <- Vote_max_slides_SXMI[match(SXMI_Clinical$IMID,names(Vote_max_slides_SXMI))]
test=as.data.frame(Vote_max_slides_SXMI)
labels <- factor(Vote_max_slides_SXMI)
legend.labs <- as.vector(na.omit(unique(labels)))

input <- as.data.frame(cbind(SXMI_Clinical$OS_Time/30,SXMI_Clinical$OS_Event)) 
input$V1 <- as.numeric(input$V1)
input$V1 <- as.numeric(input$V1)
SXMI_OS <- myplot(input,labels,ylab="Overall survival",font = "sans",
                  risk.table = T,risk.table.ratio = 0.4,title = "SXM-I",
                  legend.pos = c(0.65,0.18),xlab="Follow up",color=c("#00468BFF", "#ED0000FF", "#42B540FF", "#0099B4FF","black"))

input <- as.data.frame( cbind(SXMI_Clinical$RFS_Time/30,SXMI_Clinical$RFS_Event)) 
input$V1 <- as.numeric(input$V1)
SXMI_DFS <- myplot(input,labels,ylab="Disease-free survival",font = "sans",
                  risk.table = T,risk.table.ratio = 0.4,title = "SXM-I",
                  legend.pos = c(0.65,0.18),xlab="Follow up",color=c("#00468BFF", "#ED0000FF", "#42B540FF", "#0099B4FF"))

#Figure 5g
# 选择所需的列
load("./SXMII_Clinical.rdata")
load("./SXMII_SOFs.rdata")
# 保存为 .rdata 文件
Vote_max_slides_SXMII <- list()
xtest_SXMII<- SXMII_SOFs[,colnames(SXMI_SOFs_310)]
xtest_SXMII <- scale(xtest_SXMII)
Pred_SXMII <- predict(rfout,xtest_SXMII)
pred_SXMII_prob <- predict(rfout,xtest_SXMII, probability=TRUE)

# major vote for each patien
Names_SXMII <- substr(rownames(SXMII_SOFs),3,9)
uniqueName_SXMII <- unique(Names_SXMII)

for (xxx in uniqueName_SXMII) {
  ind <- which(Names_SXMII == xxx)  
  all_result <- Pred_SXMII[ind[1]:ind[length(ind)]]
  frequency_table <- table(all_result)
  if (sum(frequency_table == max(frequency_table)) >= 2) {
    back <- NA
  }else {
    most_frequent_element <- names(frequency_table)[which.max(frequency_table)]
    back <- most_frequent_element
  }
  if (frequency_table[which.max(frequency_table)] != length(ind) && frequency_table[4] > 0) {
    back <- "ECMS4"
  }
  Vote_max_slides_SXMII[[xxx]] <- back
}

names(Vote_max_slides_SXMII) <- uniqueName_SXMII
Vote_max_slides_SXMII <- do.call(c,Vote_max_slides_SXMII)

Vote_max_slides_SXMII <- Vote_max_slides_SXMII[match(SXMII_Clinical$IMID,names(Vote_max_slides_SXMII))]

factor_labels <- labels(Vote_max_slides_SXMII)


SXMII_clinical_M1 <- SXMII_Clinical[match(names(Vote_max_slides_SXMII),SXMII_Clinical$IMID),]
SXMII_clinical_M1$OS_Event <- str_replace_all(SXMII_clinical_M1$OS_Event,"Deceased","1")
SXMII_clinical_M1$OS_Event <- str_replace_all(SXMII_clinical_M1$OS_Event,"Living","0")
SXMII_clinical_M1$OS_Event[which(SXMII_clinical_M1$OS_Event=="Loss to follow-up")] <- NA
SXMII_clinical_M1 <- SXMII_clinical_M1[!is.na(SXMII_clinical_M1$OS_Event),]
SXMII_clinical_M1$OS_Event <- as.numeric(SXMII_clinical_M1$OS_Event)
Vote_max_slides_SXMII <- Vote_max_slides_SXMII[match(SXMII_clinical_M1$IMID,names(Vote_max_slides_SXMII))]

labels <- factor(Vote_max_slides_SXMII)
legend.labs <- as.vector(na.omit(unique(labels)))
input <- as.data.frame(cbind((SXMII_clinical_M1$OS_Time),SXMII_clinical_M1$OS_Event))
input$V1 <- as.numeric(input$V1)

SXMII_OS <- myplot(input,labels,ylab="Overall survival",font = "sans",
                  risk.table = T,risk.table.ratio = 0.4,title = "SXM-II",
                  legend.pos = c(0.65,0.18),xlab="Follow up",color=c("#00468BFF", "#ED0000FF", "#42B540FF", "#0099B4FF","black"))
```

```{r}
#Figure 5E
#SXMI——sankeyplot_patient_level
library(ggalluvial)

#final_predict <- read.csv("./SXMIpredict_patient_level.csv")
#ture_label <- read.csv("./label4patients.csv")
sankeydf <- data.frame(y_pred = final_predict$Vote_max_slides_SXMI, y_true = SXMI_Clinical$SNF)
sankeydf <- sankeydf[complete.cases(sankeydf), ]
sankeydf$y_pred <- paste("im-", sankeydf$y_pred, sep = "")

colors <- c("#00468BFF", "#ED0000FF", "#42B540FF", "#0099B4FF")
Sankey_patient <- ggplot(sankeydf,
       aes(y =NULL,
           axis1 = y_pred, axis2 = y_true))+
  geom_alluvium(aes(fill = y_pred))+
  geom_stratum() +
 geom_text(stat = "stratum", aes(label = after_stat(stratum)),reverse = TRUE, size = 3,angle=2,discern = TRUE)+
  scale_x_continuous(breaks = 1:2, labels = c("IM_ECMS", "ECMS"))+
  scale_fill_manual(values = colors) +
  theme(legend.position = "none") +
 ggtitle(" ")
```


```{r}
#Figure 5F
library(caret)
library(ggplot2)
sankeydf$y_true <- paste("im-ECMS", sankeydf$y_true, sep = "")

confusion_matrix <- confusionMatrix(as.factor(sankeydf$y_pred), as.factor(sankeydf$y_true))

print(confusion_matrix)

cm_table <- as.table(confusion_matrix$table)

cm_df <- as.data.frame(cm_table)
colnames(cm_df) <- c("Prediction", "Reference", "Freq")

confusion <- ggplot(cm_df, aes(x = Reference, y = Prediction, fill = FrSXMI)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Freq), vjust = 1) +
  scale_fill_gradient(low = "#B5E6D4", high = "#1B4242") +
  theme_minimal() +
  labs(title = "Confusion Matrix", x = "True Label", y = "Predicted Label") +
  theme(plot.title = element_text(hjust = 0.5))
```
